from routers.signin_routes import *
from routers.booking_routes import *
from routers.admin_room_routes import *
from routers.admin_room_type_routes import *
from routers.admin_service_routes import *
from routers.admin_booking_routes import *
from routers.admin_booking_service_routes import *
from routers.admin_payment_routes import *
from routers.admin_invoice_routes import *
from routers.admin_user_routes import *
from routers.admin_role_routes import *
from routers.admin_additional_charges_routes import *
from routers.admin_stats import *
from routers.index_routes import *
